// archive/web-react/components/AuthenticateWithGoogle.tsx
import Image from "next/image"
import octGoogleWorkspace from '@/assets/images/externals/logo/oct_gworkspace.png'
import { signIn } from "@/auth"

export default function AuthGoogleButton() {
    async function authenticate() {
        "use server";
        await signIn("google")
    }
    return (
        <form
            action={authenticate}>
            <button className="group px-2 py-4 w-full rounded-md flex items-center justify-center gap-2 border-[1px] border-zinc-700 border-opacity-50 shadow-md text-zinc-800 font-sans text-lg font-medium active:bg-oct-darkgreen active:text-white transition-colors duration-700">
                <Image
                    src={octGoogleWorkspace}
                    alt="A picture of the OCT Logo with a modified Google logo to resemble the words OC."
                    width={64}
                    className="group-active:grayscale"
                />
                <span>Google Workspace</span>
            </button>
        </form>
    )
}

// apps/web-vue/components/buttons/AuthenticateWithGoogle.vue
<template>
    <button class="border-[1px] border-gray-600 px-4 py-4 w-full flex items-center justify-center gap-2 transition-all hover:shadow-2xl rounded-md active:bg-oct-green active:dark:bg-white group">
        <img src="~/assets/images/externals/logo/oct_gworkspace.png" alt="" class="w-16 group-active:grayscale">
        <p class="font-medium text-xl text-gray-800 dark:text-gray-200 group-active:text-gray-200 dark:group-active:text-gray-800">Google Workspace</p>
    </button>
</template>
